name: Create Environment

permissions:
  id-token: write
  contents: read

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    name: Setup
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.setup.outputs.name }}
      type: ${{ steps.setup.outputs.type }}
    steps:
      - name: ADE Setup
        id: setup
        uses: colbylwilliams/deployment-environments@main
        with:
          action: setup

  create:
    name: Create
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    needs: setup
    environment: ${{ needs.setup.outputs.type }}

    steps:
      - uses: actions/checkout@v3

      # - name: Build ADE.Tutorial
      #   run: dotnet publish ./ADE.Tutorial -c Release -o ./publish && (cd ./publish && zip -r ../publish.zip .)

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Create
        uses: colbylwilliams/deployment-environments@main
        with:
          action: create
          parameters: '{ "name": "${{ needs.setup.outputs.name }}" }'

      # - name: Deploy ADE.Tutorial
      #   run: |
      #     az functionapp deployment source config-zip --name ${{ needs.setup.outputs.name }} --src publish.zip \
      #         --subscription ${{ steps.create.outputs.subscription }} --resource-group ${{ steps.create.outputs.resource-group }}

      #     echo "- [View environment resources in the Azure portal](${{ needs.setup.outputs.portal-url }})" >> $GITHUB_STEP_SUMMARY
      #     echo "- [View the deployed API](https://${{ needs.setup.outputs.name }}.azurewebsites.net/api/time)" >> $GITHUB_STEP_SUMMARY
